### ISSUE TITLE
Créer le système de module

### ISSUE THREAD

**Issue by tcrepy** [PA-Plasma/annual-project#23]
# New feature:
On a besoin de lister les modules disponibles
Les modules pourrait être listés dans une table par exemple
Dans la création d'event on pourrait avoir un switch case en fonction de la selection de l'utilisateur et les actions à accomplir

## Technical explainations
- creation d'une entité Module
- crud
- liaison event -> modules

**Comment by tcrepy** [comment]
Il a été décidé qu'on allait gérer tous les modules existants dans une entité `Modules`
Il faudrait pouvoir gérer chaque module par un service `Module_nom_du_module` qui implémenterai une interface `ModuleInterface` 

Pour un service `Module` on aurait des entités liés au module en question

Depuis un service `ModulesHelper` on doit pouvoir accéder aux différents modules existants en fonction de ceux qui ont été activés sur un event.

**Comment by tcrepy** [comment]
Interface Module (idée)
```php
interface ModuleInterface {
    public function getForm();

    public function render();
}
```

**Comment by WaximeA** [comment]
FAIT : 

- Création de l'entité **Modules**
- Ajout du slug et des différents Traits
- Création du crud **Back/Modules**
- Intégration du form type et de l'affichage de l'entité comme les autres
- Ajout de la liaison **Many to Many** entre l'entité **Event** et **Module**
- Ajout d'un **choice type** des modules disponibles dans le formulaire de création d'un événement (front pour l'instant)
- Affichage des modules sélectionnés sur les pages du **crud front module**

Push sur la branche **feat/modules**

Si quelqu'un a des questions, n'hésitez pas. Je continue ça demain 👍
